Overview of Below Code: 
* The below code organizes the dataframe and pulls the graded data from the other script in order to create dummy variables and prepare it for the OLS regression. It produces the summary table from the OLS and also creates a visualizations for some variables. This was used to create the OLS for the simulated data for our third milestone, and the OLS for our final paper. 

Defining the function: 

-Function Name: OLS Regression and Visualization
    -Purpose: The code runs the full regression after the other scripts provided the code to input the graded questions. It creates the dummy variables and uses them to run the OLS regression, and it visualizes one of the variables. 
    
  -Parameters: It takes the graded scores from the other script dedicated to regrading, the original cleaned dataframe and merges them together, and takes in dummy variables, all used as independent variables, and regresses them against the final score.

Packages Used for Data Analysis

In [8]:
import numpy as np
import statsmodels.api as sm
import statsmodels.formula.api as smf
import pandas as pd

Loading Data

In [9]:
# preassessment= "/Users/jeremyrodriguez/Dropbox (Dartmouth College)/QSS20_FinalProject/training_data/IDD-MH Med Student Curriculum Consent_Pre Assessment_October 10, 2022_14.35.csv"
# pre = pd.read_csv(preassessment)

# Using the Med Student Pre Assessment Data that is found on our Shared Google Drive
pre = pd.read_csv('../Downloads/Med student pre assessment 2.8.23 - Med student pre assessment 2.8.23.csv')
 
pre

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,...,Q12,Q13,Q22,Q23,Q53_1,Q53_2,Q53_3,Q53_4,Q53_5,SC0
0,Start Date,End Date,Response Type,IP Address,Progress,Duration (in seconds),Finished,Recorded Date,Response ID,Recipient Last Name,...,Which of the following are best practices in c...,If a patient with IDD-MH is acting out in the ...,Which is not a treatment approach that people ...,Which of the medications below are among those...,Please rate your level of agreement with the f...,Please rate your level of agreement with the f...,Please rate your level of agreement with the f...,Please rate your level of agreement with the f...,Please rate your level of agreement with the f...,Score
1,"{""ImportId"":""startDate"",""timeZone"":""America/De...","{""ImportId"":""endDate"",""timeZone"":""America/Denv...","{""ImportId"":""status""}","{""ImportId"":""ipAddress""}","{""ImportId"":""progress""}","{""ImportId"":""duration""}","{""ImportId"":""finished""}","{""ImportId"":""recordedDate"",""timeZone"":""America...","{""ImportId"":""_recordId""}","{""ImportId"":""recipientLastName""}",...,"{""ImportId"":""QID12""}","{""ImportId"":""QID13""}","{""ImportId"":""QID22""}","{""ImportId"":""QID23""}","{""ImportId"":""QID53_1""}","{""ImportId"":""QID53_2""}","{""ImportId"":""QID53_3""}","{""ImportId"":""QID53_4""}","{""ImportId"":""QID53_5""}","{""ImportId"":""SC_9zzmf9m2yTVbssm""}"
2,3/23/2022 9:42,3/23/2022 9:46,Survey Preview,NaN,100,229,TRUE,3/23/2022 9:46,R_djvqzijTB5L2Pjb,NaN,...,"Ask your patient exploratory questions,Talk to...","Discipline the person to get them to behave,Ge...","Extensive, long-term behavior modification tre...","lithium,quetiapine,divalproex",NaN,NaN,NaN,NaN,NaN,2
3,3/24/2022 13:30,3/24/2022 13:30,Survey Preview,NaN,100,4,TRUE,3/24/2022 13:30,R_2zqcz6JEOzFKMf0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3/25/2022 10:00,3/25/2022 10:00,IP Address,184.174.134.134,100,9,TRUE,3/25/2022 10:00,R_12SvBoipzeVQw2d,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,1/5/2023 6:12,1/5/2023 6:15,IP Address,129.170.195.199,52,185,FALSE,1/12/2023 6:15,R_1F8lTLDjFsvTPIG,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,1/5/2023 6:13,1/5/2023 6:16,IP Address,129.170.195.196,52,214,FALSE,1/12/2023 6:17,R_1LhS0pfNjndIluO,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,1/5/2023 6:16,1/5/2023 6:18,IP Address,129.170.195.220,52,125,FALSE,1/12/2023 6:18,R_ers03KIuDkTjyZr,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,1/30/2023 16:41,1/30/2023 16:51,IP Address,130.189.175.200,100,561,TRUE,1/30/2023 16:51,R_1qdHEmkAfsxhxyD,NaN,...,Ask your patient exploratory questions,"Defer to the person’s caregiver,Give the patie...","Extensive, long-term behavior modification tre...",risperidone,Somewhat Disagree,Somewhat Disagree,Somewhat Disagree,Somewhat Disagree,Strongly Agree,17
101,1/30/2023 7:31,1/31/2023 12:06,IP Address,76.119.230.62,6,102875,FALSE,2/7/2023 12:09,R_OkRiNSpATkUFgZ3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Data Cleaning/Preprocessing

In [10]:
##Dropping irrelevant rows for preparation
pre_clean= pre.drop(0)

pre_clean=pre_clean.drop(1)

pre_clean

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,...,Q12,Q13,Q22,Q23,Q53_1,Q53_2,Q53_3,Q53_4,Q53_5,SC0
2,3/23/2022 9:42,3/23/2022 9:46,Survey Preview,NaN,100,229,TRUE,3/23/2022 9:46,R_djvqzijTB5L2Pjb,NaN,...,"Ask your patient exploratory questions,Talk to...","Discipline the person to get them to behave,Ge...","Extensive, long-term behavior modification tre...","lithium,quetiapine,divalproex",NaN,NaN,NaN,NaN,NaN,2
3,3/24/2022 13:30,3/24/2022 13:30,Survey Preview,NaN,100,4,TRUE,3/24/2022 13:30,R_2zqcz6JEOzFKMf0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3/25/2022 10:00,3/25/2022 10:00,IP Address,184.174.134.134,100,9,TRUE,3/25/2022 10:00,R_12SvBoipzeVQw2d,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,3/28/2022 14:40,3/28/2022 14:40,IP Address,174.19.98.252,100,5,TRUE,3/28/2022 14:40,R_2SH7E5DZhOsRjZh,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,3/28/2022 14:40,3/31/2022 6:21,IP Address,174.19.98.252,100,229238,TRUE,3/31/2022 6:21,R_3PhIpFxHA8Ho4s8,NaN,...,Know that people with the same disability will...,Get a copy of their behavior plan for the next...,"Extensive, long-term behavior modification tre...",lithium,Strongly Disagree,Strongly Disagree,Strongly Disagree,Strongly Disagree,Strongly Disagree,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,1/5/2023 6:12,1/5/2023 6:15,IP Address,129.170.195.199,52,185,FALSE,1/12/2023 6:15,R_1F8lTLDjFsvTPIG,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,1/5/2023 6:13,1/5/2023 6:16,IP Address,129.170.195.196,52,214,FALSE,1/12/2023 6:17,R_1LhS0pfNjndIluO,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,1/5/2023 6:16,1/5/2023 6:18,IP Address,129.170.195.220,52,125,FALSE,1/12/2023 6:18,R_ers03KIuDkTjyZr,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,1/30/2023 16:41,1/30/2023 16:51,IP Address,130.189.175.200,100,561,TRUE,1/30/2023 16:51,R_1qdHEmkAfsxhxyD,NaN,...,Ask your patient exploratory questions,"Defer to the person’s caregiver,Give the patie...","Extensive, long-term behavior modification tre...",risperidone,Somewhat Disagree,Somewhat Disagree,Somewhat Disagree,Somewhat Disagree,Strongly Agree,17
101,1/30/2023 7:31,1/31/2023 12:06,IP Address,76.119.230.62,6,102875,FALSE,2/7/2023 12:09,R_OkRiNSpATkUFgZ3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
#Initial milestone cleaning

#Q6_correct answers column
pre_clean['Q6_correct']= np.where(pre_clean['Q6']== 'Anxiety, Depression, & Trauma-Related Disorders', 1, 0)
pre_clean.loc[(pre_clean['Q6'].isna()) & (pre_clean['Q6_correct'] == 0), 'Q6_correct'] = np.nan


#Q37_correct answers column
pre_clean['Q37_correct']= np.where(pre_clean['Q37']== 'Talking to inanimate objects', 1, 0)
pre_clean.loc[(pre_clean['Q37'].isna()) & (pre_clean['Q37_correct'] == 0), 'Q37_correct'] = np.nan


#Q13_correct answers column

#This one was multiple choice but only one answer is correct so basically everone got it wrong

pre_clean['Q13_correct']= np.where(pre_clean['Q13']== 'Defer to the person’s caregiver', 1, 0)
pre_clean.loc[(pre_clean['Q13'].isna()) & (pre_clean['Q13_correct'] == 0), 'Q13_correct'] = np.nan

#Q22_correct answers column

pre_clean['Q22_correct']= np.where(pre_clean['Q22']== 'Combination treatment, including pharmacotherapy/manualized psychotherapies', 1, 0)
pre_clean.loc[(pre_clean['Q22'].isna()) & (pre_clean['Q22_correct'] == 0), 'Q22_correct'] = np.nan

#Looking at columns
pre_clean
pre_clean.columns

Index(['StartDate', 'EndDate', 'Status', 'IPAddress', 'Progress',
       'Duration (in seconds)', 'Finished', 'RecordedDate', 'ResponseId',
       'RecipientLastName', 'RecipientFirstName', 'RecipientEmail',
       'ExternalReference', 'LocationLatitude', 'LocationLongitude',
       'DistributionChannel', 'UserLanguage', 'Q52', 'Q1', 'Q1_9_TEXT', 'Q25',
       'Q26', 'Q26_6_TEXT', 'Q27', 'Q27_9_TEXT', 'Q28', 'Q28_4_TEXT', 'Q29',
       'Q29_3_TEXT', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q10', 'Q30', 'Q31', 'Q34',
       'Q36', 'Q37', 'Q39', 'Q11', 'Q12', 'Q13', 'Q22', 'Q23', 'Q53_1',
       'Q53_2', 'Q53_3', 'Q53_4', 'Q53_5', 'SC0', 'Q6_correct', 'Q37_correct',
       'Q13_correct', 'Q22_correct'],
      dtype='object')

In [12]:
#Removing NaN values
pre_clean = pre_clean[~pre_clean["SC0"].isna()]

The Regrading Process for Simulated Data (from other script)

In [47]:
#Dictionary for grading free response questions, from other script

import pandas as pd
import ipywidgets as widgets

questions_dict = {
    "question": [
        'The most common mental health conditions experienced by people with intellectual and developmental disabilities are:',
        'Which of the following statements are true about systems of care for people with intellectual and developmental disabilities? Select all correct answers.',
        'What are the three (3) most common medical conditions experienced by people with IDD?',
        'Which of the following statements are true when assessing aggression in patients with intellectual and developmental disabilities? Select all correct answers.',
        'Which of the following is not a common presentation of anxiety in people with intellectual and developmental disabilities and limited communication skills?',
        'Signs of psychosis in people with intellectual and developmental disabilities include which of the following? Select all correct answers.',
        'Which of the following are best practices in communicating with patients with IDD-MH and their families? Select all correct answers.',
        'If a patient with IDD-MH is acting out in the waiting room, you and your waiting room staff should: Select all correct answers.',
        'Which is not a treatment approach that people diagnosed with intellectual and developmental disabilities and OCD may need?',
        'Which of the medications below are among those that should be considered first when treating patients with intellectual and developmental disabilities and mania?Select all correct answers.'
    ],

    "options": [
        ['Personality Disorders, Psychotic Disorders & Trauma-Related Disorders','Anxiety, Depression, & Trauma-Related Disorders','Bipolar Disorder, Psychotic Disorders, & Trauma-Related Disorders','Depression, Psychotic Disorders & Schizophrenia'],
        ['In order to receive IDD services, the person must have a diagnosed intellectual or developmental disability, and must have impaired adaptive functioning','Medical providers may need to engage family members and other caregivers in the patient’s care','All people with IDD receive the same array of services', 'The majority of people with IDD receive care in institutions','The person’s case manager/service coordinator from the developmental disabilities service agency could be helpful at medical appointments'],
        ['Neurological disorder(s)','Leg pain', 'Asthma','Pain (ex:dental, ear)','Kidney Disease','Cardiovascular disease','GI problems (ex: constipation, GERD)'],
        ['Medical/biological issues should be ruled out first','Some genetic disorders can cause increased risk of mental health or medical issues','Constipation, dental pain and gastroesphogeal reflux are common medical causes of aggression that should be considered',"Aggression should be managed by your state's developmental disabilities service agency", "Behavior is a form of communication",'Psychosocial stressors don\'t need to be considered'],
        ['Irritability or aggression','Running away','Talking to inanimate objects','Withdrawal','Staring into space', 'Increased repetitive speech and movement'],
        ['talking to themselves, monologue','having an imaginary friend','Unusual interests', 'Lip smacking','Auditory hallucinations that are intrusive and distressing','Change from baseline behavior','Covering ears/eyes'],
        ['Ask your patient exploratory questions','Talk to, and engage with, the patients’ caregiver rather than the patient themselves','Ask questions other than that directly pertain to the reason for the visit', 'Know that people with the same disability will always communicate in the same way'],
        ['Discipline the person to get them to behave','Get a copy of their behavior plan for the next time they are in your office','Administer a PRN',"Defer to the person's caregiver", 'Give the patient the option to wait outside or in the car']
        ],

        "correct_answers": [
        ['Anxiety, Depression, & Trauma-Related Disorders'],
        ['In order to receive IDD services, the person must have a diagnosed intellectual or developmental disability, and must have impaired adaptive functioning'],
        ['Medical providers may need to engage family members and other caregivers in the patient’s care'],
        ['The person’s case manager/service coordinator from the developmental disabilities service agency could be helpful at medical appointments'],
        ['Neurological disorder(s)','Pain (ex: dental, ear)','GI problems (ex: constipation, GERD)'],
        ['Medical/biological issues should be ruled out first','Some genetic disorders can cause increased risk of mental health or medical issues'],
        ['Constipation, dental pain and gastroesphogeal reflux are common medical causes of aggression that should be considered','Behavior is a form of communication'],                 
        ['Talking to inanimate objects'],
        ['Auditory hallucinations that are intrusive and distressing','Change from baseline behavior','Covering ears/eyes'],
        ['Ask your patient exploratory questions','Ask questions other than that directly pertain to the reason for the visit'],
        ['Defer to the person’s caregiver'],
        ['Combination treatment, including pharmacotherapy/manualized psychotherapies'],
        ['lithium','divalproex','aripiprazole','risperidone']]
        
        }

# questions_dict

Preliminary Data Analysis

In [171]:
#Importing pandas and NumPy
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
import random
import re

In [13]:
#Means of Correct Scores for Multiple Choice Answers


correct_columns= ['Q6_correct','Q37_correct', 'Q13_correct', 'Q22_correct']  


correct_percentages={}
for col in correct_columns:
    percentage_correct = pre_clean[col].mean() *100
    correct_percentages[col] = percentage_correct

summary_df = pd.DataFrame.from_dict(correct_percentages, orient='index', columns=['Percentage correct'])
summary_df

             Percentage correct
Q6_correct            86.075949
Q37_correct           53.164557
Q13_correct            1.265823
Q22_correct           22.784810

In [14]:
pre_clean["Q6_correct_cat"] = pre_clean["Q6_correct"].values.astype("str")
pre_clean["Q6_correct_cat"].value_counts()

1.0    68
0.0    11
Name: Q6_correct_cat, dtype: int64

In [152]:
#Initial ideal code
#results = smf.ols('SC0 ~ Q6_correct_cat', data = pre_clean)
#results.fit()
#results.summary()

In [101]:
#CODE FOR CREATING SIMULATED DATA

import random

partial_credit_questions = {
    'Q31': 0.8,
    'Q34': 0.6,
    'Q36': 0.7,
    'Q39': 0.4,
    'Q12': 0.8,
    'Q22': 0.5
}

decimal_probabilities = {
    'Q31': 0.1,
    'Q34': 0.3,
    'Q36': 0.4,
    'Q39': 0.3,
    'Q12': 0.1,
    'Q22': 0.2
}

binary_values = []

for i in range(79):
    row = []
    for j in range(9):
        if df.columns[j] in partial_credit_questions and random.random() < partial_credit_questions[df.columns[j]]:
            if random.random() < decimal_probabilities[df.columns[j]]:
                row.append(round(random.uniform(0.5, 1), 1))
            else:
                row.append(1)
        else:
            row.append(random.randint(0, 1))
    binary_values.append(row)


df = pd.DataFrame(binary_values, columns=['Q6', 'Q31', 'Q34', 'Q36', 'Q37', 'Q39', 'Q12', 'Q13', 'Q22'])



print(df.tail(n=40))

    Q6  Q31  Q34  Q36  Q37  Q39  Q12  Q13  Q22
39   1  1.0  1.0  1.0    1  1.0  1.0    0  1.0
40   1  1.0  1.0  0.0    1  1.0  1.0    0  1.0
41   0  1.0  0.8  1.0    0  1.0  1.0    0  1.0
42   1  0.0  0.8  0.0    0  0.0  1.0    1  1.0
43   0  1.0  0.0  1.0    0  1.0  1.0    0  1.0
44   1  1.0  1.0  1.0    0  1.0  1.0    1  0.0
45   0  1.0  0.0  1.0    1  0.5  1.0    0  1.0
46   1  1.0  0.0  1.0    0  1.0  1.0    0  0.0
47   1  1.0  0.0  1.0    1  1.0  1.0    0  1.0
48   1  1.0  1.0  1.0    0  1.0  1.0    0  1.0
49   1  0.0  1.0  0.0    1  1.0  1.0    1  1.0
50   0  0.7  1.0  1.0    0  1.0  1.0    1  1.0
51   0  1.0  0.0  0.5    0  1.0  0.9    0  1.0
52   1  1.0  1.0  1.0    0  1.0  1.0    0  1.0
53   0  1.0  0.0  0.7    1  1.0  1.0    1  1.0
54   1  1.0  0.0  1.0    0  0.0  1.0    0  1.0
55   0  1.0  0.0  0.0    1  0.7  1.0    1  0.0
56   1  1.0  1.0  1.0    1  1.0  1.0    1  1.0
57   0  1.0  1.0  0.5    1  1.0  1.0    1  1.0
58   1  1.0  0.0  1.0    1  0.0  1.0    1  1.0
59   0  1.0  1.0  1.0    1  0.0  1.0    0  1.0
60   1  1.0  1.0  1.0    1  1.0  1.0    0  0.5
61   0  1.0  0.6  1.0    1  1.0  1.0    0  1.0
62   0  1.0  1.0  0.9    1  1.0  1.0    0  1.0
63   1  1.0  1.0  1.0    0  1.0  1.0    0  1.0
64   0  1.0  0.6  1.0    0  1.0  1.0    0  0.0
65   1  0.0  1.0  1.0    0  1.0  1.0    0  1.0
66   1  1.0  0.5  0.6    1  1.0  0.0    1  1.0
67   1  1.0  0.0  1.0    1  0.0  1.0    0  1.0
68   1  1.0  1.0  1.0    0  0.0  1.0    1  1.0
69   1  1.0  1.0  1.0    1  0.0  1.0    0  1.0
70   1  1.0  1.0  0.0    0  0.0  1.0    0  1.0
71   0  0.8  1.0  1.0    0  0.0  1.0    0  1.0
72   1  1.0  1.0  1.0    0  1.0  1.0    0  1.0
73   1  0.0  1.0  1.0    1  1.0  0.5    0  1.0
74   1  0.0  1.0  1.0    0  1.0  0.0    0  0.0
75   0  1.0  0.0  0.6    0  1.0  1.0    0  0.0
76   0  1.0  1.0  1.0    1  1.0  1.0    1  1.0
77   1  0.0  1.0  1.0    0  1.0  1.0    0  0.0
78   1  1.0  1.0  1.0    1  0.0  0.0    0  0.8

In [17]:
#Code for running real data .csv
data = pd.read_csv('../Downloads/scores_df.csv')
data.reset_index(drop=True)
pre_clean.reset_index(drop=True)
pre_clean.columns

Index(['StartDate', 'EndDate', 'Status', 'IPAddress', 'Progress',
       'Duration (in seconds)', 'Finished', 'RecordedDate', 'ResponseId',
       'RecipientLastName', 'RecipientFirstName', 'RecipientEmail',
       'ExternalReference', 'LocationLatitude', 'LocationLongitude',
       'DistributionChannel', 'UserLanguage', 'Q52', 'Q1', 'Q1_9_TEXT', 'Q25',
       'Q26', 'Q26_6_TEXT', 'Q27', 'Q27_9_TEXT', 'Q28', 'Q28_4_TEXT', 'Q29',
       'Q29_3_TEXT', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q10', 'Q30', 'Q31', 'Q34',
       'Q36', 'Q37', 'Q39', 'Q11', 'Q12', 'Q13', 'Q22', 'Q23', 'Q53_1',
       'Q53_2', 'Q53_3', 'Q53_4', 'Q53_5', 'SC0'],
      dtype='object')

In [14]:
pre_clean = pre_clean[(pre_clean["Finished"] == "TRUE")]

pre_clean = pre_clean[(pre_clean["Q52"] != 'Click here if you decline to participate in the research study')]

df_q_only = pre_clean.iloc[:, 20:]

#df_q_only = df_q_only.drop(["Q10", "Q30", "Q11","Q53_1","Q53_2","Q53_3","Q53_4","Q53_5","SC0"], axis=1)

#df_q_only.head()

analyze = df_q_only ; analyze

analyze.reset_index(drop = True)

,Q25,Q26,Q26_6_TEXT,Q27,Q27_9_TEXT,Q28,Q28_4_TEXT,Q29,Q29_3_TEXT,Q2,...,Q12,Q13,Q22,Q23,Q53_1,Q53_2,Q53_3,Q53_4,Q53_5,SC0
0,33-40,Non-binary,NaN,Asian,NaN,Non-Hispanic,NaN,English,NaN,None,...,"Ask your patient exploratory questions,Talk to...","Discipline the person to get them to behave,Ge...","Extensive, long-term behavior modification tre...","lithium,quetiapine,divalproex",NaN,NaN,NaN,NaN,NaN,2
1,41-50,Male,NaN,Other,NaN,Non-Hispanic,NaN,English,NaN,Moderate amount,...,Know that people with the same disability will...,Get a copy of their behavior plan for the next...,"Extensive, long-term behavior modification tre...",lithium,Strongly Disagree,Strongly Disagree,Strongly Disagree,Strongly Disagree,Strongly Disagree,-1
2,26-32,Female,NaN,Asian,NaN,Other,Tamil Indian,English,NaN,Some,...,Ask your patient exploratory questions,Get a copy of their behavior plan for the next...,"Extensive, long-term behavior modification tre...","aripiprazole,risperidone",Strongly Disagree,Strongly Agree,Somewhat Disagree,Somewhat Disagree,Somewhat Agree,14
3,26-32,Male,NaN,White,NaN,Non-Hispanic,NaN,English,NaN,Some,...,"Ask your patient exploratory questions,Ask que...",Give the patient the option to wait outside or...,"Extensive, long-term behavior modification tre...",risperidone,Strongly Disagree,Strongly Disagree,Somewhat Disagree,Somewhat Disagree,Somewhat Agree,18
4,33-40,Female,NaN,White,NaN,Non-Hispanic,NaN,English,NaN,Some,...,"Ask your patient exploratory questions,Ask que...",Get a copy of their behavior plan for the next...,"Extensive, long-term behavior modification tre...","lithium,divalproex",Strongly Disagree,Somewhat Agree,Strongly Disagree,Somewhat Agree,Somewhat Agree,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,26-32,Female,NaN,Hispanic,Latinx,Hispanic/Latino of any race,NaN,English,NaN,Some,...,Ask your patient exploratory questions,Get a copy of their behavior plan for the next...,"Extensive, long-term behavior modification tre...",lithium,Strongly Disagree,Somewhat Disagree,Strongly Disagree,Somewhat Disagree,Somewhat Agree,10
75,18-25,Female,NaN,Hispanic,NaN,Hispanic/Latino of any race,NaN,English,NaN,Some,...,"Ask your patient exploratory questions,Ask que...",Get a copy of their behavior plan for the next...,An extensive review of previous diagnoses and ...,"divalproex,aripiprazole",Somewhat Disagree,Somewhat Disagree,Somewhat Agree,Strongly Agree,Somewhat Agree,14
76,18-25,Male,NaN,White,NaN,Non-Hispanic,NaN,English,NaN,Some,...,Ask your patient exploratory questions,Get a copy of their behavior plan for the next...,"Combination treatment, including pharmacothera...",lithium,Somewhat Disagree,Somewhat Disagree,Somewhat Disagree,Somewhat Agree,Somewhat Disagree,11
77,18-25,Female,NaN,Other,NaN,Non-Hispanic,NaN,English,NaN,Some,...,Ask questions other than that directly pertain...,Give the patient the option to wait outside or...,"Combination treatment, including pharmacothera...",lithium,Strongly Disagree,Somewhat Disagree,Somewhat Disagree,Somewhat Agree,Somewhat Agree,11
78,26-32,Female,NaN,White,NaN,Non-Hispanic,NaN,English,NaN,Extensive,...,Ask your patient exploratory questions,"Defer to the person’s caregiver,Give the patie...","Extensive, long-term behavior modification tre...",risperidone,Somewhat Disagree,Somewhat Disagree,Somewhat Disagree,Somewhat Disagree,Strongly Agree,17

In [15]:
#Dropping original columns to prepare for drop
#analyze.drop(["Q6",  "Q31",  "Q34",  "Q36",  "Q37",  "Q39",  "Q12",  "Q13",  "Q22"], axis=1)
analyze = analyze.reset_index(drop=True)
analyze

,Q25,Q26,Q26_6_TEXT,Q27,Q27_9_TEXT,Q28,Q28_4_TEXT,Q29,Q29_3_TEXT,Q2,...,Q12,Q13,Q22,Q23,Q53_1,Q53_2,Q53_3,Q53_4,Q53_5,SC0
0,33-40,Non-binary,NaN,Asian,NaN,Non-Hispanic,NaN,English,NaN,None,...,"Ask your patient exploratory questions,Talk to...","Discipline the person to get them to behave,Ge...","Extensive, long-term behavior modification tre...","lithium,quetiapine,divalproex",NaN,NaN,NaN,NaN,NaN,2
1,41-50,Male,NaN,Other,NaN,Non-Hispanic,NaN,English,NaN,Moderate amount,...,Know that people with the same disability will...,Get a copy of their behavior plan for the next...,"Extensive, long-term behavior modification tre...",lithium,Strongly Disagree,Strongly Disagree,Strongly Disagree,Strongly Disagree,Strongly Disagree,-1
2,26-32,Female,NaN,Asian,NaN,Other,Tamil Indian,English,NaN,Some,...,Ask your patient exploratory questions,Get a copy of their behavior plan for the next...,"Extensive, long-term behavior modification tre...","aripiprazole,risperidone",Strongly Disagree,Strongly Agree,Somewhat Disagree,Somewhat Disagree,Somewhat Agree,14
3,26-32,Male,NaN,White,NaN,Non-Hispanic,NaN,English,NaN,Some,...,"Ask your patient exploratory questions,Ask que...",Give the patient the option to wait outside or...,"Extensive, long-term behavior modification tre...",risperidone,Strongly Disagree,Strongly Disagree,Somewhat Disagree,Somewhat Disagree,Somewhat Agree,18
4,33-40,Female,NaN,White,NaN,Non-Hispanic,NaN,English,NaN,Some,...,"Ask your patient exploratory questions,Ask que...",Get a copy of their behavior plan for the next...,"Extensive, long-term behavior modification tre...","lithium,divalproex",Strongly Disagree,Somewhat Agree,Strongly Disagree,Somewhat Agree,Somewhat Agree,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,26-32,Female,NaN,Hispanic,Latinx,Hispanic/Latino of any race,NaN,English,NaN,Some,...,Ask your patient exploratory questions,Get a copy of their behavior plan for the next...,"Extensive, long-term behavior modification tre...",lithium,Strongly Disagree,Somewhat Disagree,Strongly Disagree,Somewhat Disagree,Somewhat Agree,10
75,18-25,Female,NaN,Hispanic,NaN,Hispanic/Latino of any race,NaN,English,NaN,Some,...,"Ask your patient exploratory questions,Ask que...",Get a copy of their behavior plan for the next...,An extensive review of previous diagnoses and ...,"divalproex,aripiprazole",Somewhat Disagree,Somewhat Disagree,Somewhat Agree,Strongly Agree,Somewhat Agree,14
76,18-25,Male,NaN,White,NaN,Non-Hispanic,NaN,English,NaN,Some,...,Ask your patient exploratory questions,Get a copy of their behavior plan for the next...,"Combination treatment, including pharmacothera...",lithium,Somewhat Disagree,Somewhat Disagree,Somewhat Disagree,Somewhat Agree,Somewhat Disagree,11
77,18-25,Female,NaN,Other,NaN,Non-Hispanic,NaN,English,NaN,Some,...,Ask questions other than that directly pertain...,Give the patient the option to wait outside or...,"Combination treatment, including pharmacothera...",lithium,Strongly Disagree,Somewhat Disagree,Somewhat Disagree,Somewhat Agree,Somewhat Agree,11
78,26-32,Female,NaN,White,NaN,Non-Hispanic,NaN,English,NaN,Extensive,...,Ask your patient exploratory questions,"Defer to the person’s caregiver,Give the patie...","Extensive, long-term behavior modification tre...",risperidone,Somewhat Disagree,Somewhat Disagree,Somewhat Disagree,Somewhat Disagree,Strongly Agree,17

In [23]:
#Creation of dummy variables

#Races
merged_df['White'] = merged_df['Q27'].apply(lambda x: 1 if x == 'White' else 0) #Not used, as Whiteness was the reference group
merged_df['Asian'] = merged_df['Q27'].apply(lambda x: 1 if x == 'Asian' else 0)
merged_df['Hispanic'] = merged_df['Q27'].apply(lambda x: 1 if x == 'Hispanic' else 0)

#Gender
merged_df['Male'] = merged_df['Q26'].apply(lambda x: 1 if x == 'Male' else 0)
merged_df['Female'] = merged_df['Q26'].apply(lambda x: 1 if x == 'Female' else 0)

#Age
age_map = {'18-25': 1, '26-32': 2, '33-40': 3, '41-50': 4}
merged_df['Age'] = merged_df['Q25'].apply(lambda x: age_map.get(x, 0))

#Primary Language
merged_df['Primary'] = merged_df['Q29'].apply(lambda x: 1 if x == 'English' else 0)

#Experience
exp_map = {'None': 0, 'Very little': 1, 'Some': 2, 'Moderate amount': 3, 'Extensive': 4}
merged_df['Experience'] = merged_df['Q2'].apply(lambda x: exp_map.get(x, 0))

#Training 
merged_df['Training'] = merged_df['Q3'].apply(lambda x: exp_map.get(x, 0))

merged_df.head()

,Q25,Q26,Q26_6_TEXT,Q27,Q27_9_TEXT,Q28,Q28_4_TEXT,Q29,Q29_3_TEXT,Q2,...,q23_answers,White,Asian,Hispanic,Male,Female,Age,Primary,Experience,Training
0,33-40,Non-binary,NaN,Asian,NaN,Non-Hispanic,NaN,English,NaN,None,...,0.625,0,1,0,0,0,3,1,0,0
1,41-50,Male,NaN,Other,NaN,Non-Hispanic,NaN,English,NaN,Moderate amount,...,0.125,0,0,0,1,0,4,1,3,0
2,26-32,Female,NaN,Asian,NaN,Other,Tamil Indian,English,NaN,Some,...,0.250,0,1,0,0,1,2,1,2,2
3,26-32,Male,NaN,White,NaN,Non-Hispanic,NaN,English,NaN,Some,...,0.875,1,0,0,1,0,2,1,2,2
4,33-40,Female,NaN,White,NaN,Non-Hispanic,NaN,English,NaN,Some,...,0.250,1,0,0,0,1,3,1,2,1

In [25]:
merged_df['SC0'] = pd.to_numeric(merged_df['SC0'], errors='coerce')
merged_df['SC0'] = merged_df['SC0'] - 3

In [43]:
#Analyzing
import statsmodels.formula.api as smf

#Model 1
#model = smf.ols('SC0 ~ Q6_y + Q31_y + Q34_y + Q36_y + Q37_y + Q39_y + Q12_y + Q13_y + Q22_y', data=merged_df)
#result = model.fit()
#print(result.summary())

In [136]:
#Model 2
model = smf.ols('SC0 ~ Q6_y + Q31_y + Q34_y + Q36_y + Q37_y + Q39_y + Q12_y + Q13_y + Q22_y + Age + White + Asian + Hispanic + Male + Female + Primary + Experience + Training', data=merged_df)
result = model.fit()
print(result.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    SC0   R-squared:                       0.282
Model:                            OLS   Adj. R-squared:                  0.066
Method:                 Least Squares   F-statistic:                     1.308
Date:                Sun, 05 Mar 2023   Prob (F-statistic):              0.216
Time:                        23:24:07   Log-Likelihood:                -201.94
No. Observations:                  79   AIC:                             441.9
Df Residuals:                      60   BIC:                             486.9
Df Model:                          18
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      9.2082      4.885      1.885      0.064      -0.563      18.980
Q6_y           1.1013      0.914      1.205      0.233      -0.727       2.929
Q31_y          3.0165      1.371      2.200      0.032       0.274       5.759
Q34_y          0.8968      1.008      0.890      0.377      -1.120       2.913
Q36_y         -1.5076      1.375     -1.097      0.277      -4.258       1.242
Q37_y         -0.4787      0.904     -0.530      0.598      -2.287       1.330
Q39_y         -0.2405      0.997     -0.241      0.810      -2.234       1.753
Q12_y         -1.0005      1.620     -0.618      0.539      -4.241       2.240
Q13_y          0.1789      0.945      0.189      0.851      -1.711       2.069
Q22_y         -1.2478      1.073     -1.163      0.249      -3.393       0.898
Age           -0.5065      0.637     -0.795      0.430      -1.781       0.768
White          2.9564      1.336      2.212      0.031       0.283       5.630
Asian          1.8515      1.881      0.984      0.329      -1.911       5.614
Hispanic       0.7414      2.102      0.353      0.726      -3.463       4.946
Male           2.4323      3.268      0.744      0.460      -4.104       8.969
Female         1.2657      3.127      0.405      0.687      -4.989       7.521
Primary       -0.6036      2.392     -0.252      0.802      -5.388       4.181
Experience     0.2795      0.500      0.559      0.578      -0.721       1.280
Training       0.9296      0.572      1.626      0.109      -0.214       2.074
==============================================================================
Omnibus:                        2.716   Durbin-Watson:                   1.729
Prob(Omnibus):                  0.257   Jarque-Bera (JB):                2.367
Skew:                          -0.424   Prob(JB):                        0.306
Kurtosis:                       3.006   Cond. No.                         56.2
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [137]:
#Model 3
model = smf.ols('SC0 ~ Q6_y + Q31_y  + Q36_y + Q39_y + Q22_y + Age + White + Asian + Hispanic + Male + Female + Primary + Experience + Training', data=merged_df)
result = model.fit()
print(result.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    SC0   R-squared:                       0.261
Model:                            OLS   Adj. R-squared:                  0.099
Method:                 Least Squares   F-statistic:                     1.612
Date:                Sun, 05 Mar 2023   Prob (F-statistic):             0.0999
Time:                        23:38:09   Log-Likelihood:                -203.08
No. Observations:                  79   AIC:                             436.2
Df Residuals:                      64   BIC:                             471.7
Df Model:                          14
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      9.2553      4.489      2.062      0.043       0.288      18.222
Q6_y           1.1468      0.896      1.280      0.205      -0.643       2.937
Q31_y          2.6854      1.313      2.046      0.045       0.063       5.308
Q36_y         -1.8726      1.282     -1.460      0.149      -4.434       0.689
Q39_y         -0.0279      0.944     -0.030      0.976      -1.913       1.857
Q22_y         -1.2065      1.011     -1.193      0.237      -3.227       0.814
Age           -0.4854      0.612     -0.793      0.431      -1.708       0.738
White          3.0988      1.279      2.422      0.018       0.543       5.655
Asian          1.7079      1.783      0.958      0.342      -1.854       5.270
Hispanic       0.9142      2.032      0.450      0.654      -3.146       4.975
Male           1.7244      3.113      0.554      0.582      -4.494       7.943
Female         0.6307      3.010      0.210      0.835      -5.382       6.643
Primary       -0.3078      2.313     -0.133      0.895      -4.928       4.312
Experience     0.2669      0.486      0.549      0.585      -0.704       1.238
Training       1.0441      0.548      1.904      0.061      -0.051       2.140
==============================================================================
Omnibus:                        4.759   Durbin-Watson:                   1.611
Prob(Omnibus):                  0.093   Jarque-Bera (JB):                4.146
Skew:                          -0.550   Prob(JB):                        0.126
Kurtosis:                       3.224   Cond. No.                         51.2
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [21]:
#Running actual regressions on real data

merged_df = analyze.merge(data, left_index=True, right_index=True, how='right')
merged_df

,Q25,Q26,Q26_6_TEXT,Q27,Q27_9_TEXT,Q28,Q28_4_TEXT,Q29,Q29_3_TEXT,Q2,...,q6_answers,q31_answers,q34_answers,q36_answers,q37_answers,q39_answers,q12_answers,q13_answers,q22_answers,q23_answers
0,33-40,Non-binary,NaN,Asian,NaN,Non-Hispanic,NaN,English,NaN,None,...,1,1.00,1.00,1.0,0,1.000000,1.0,0,0,0.625
1,41-50,Male,NaN,Other,NaN,Non-Hispanic,NaN,English,NaN,Moderate amount,...,1,1.00,0.66,1.0,0,0.666667,1.0,0,0,0.125
2,26-32,Female,NaN,Asian,NaN,Other,Tamil Indian,English,NaN,Some,...,1,1.00,1.00,1.0,0,1.000000,1.0,0,0,0.250
3,26-32,Male,NaN,White,NaN,Non-Hispanic,NaN,English,NaN,Some,...,1,1.00,1.00,1.0,1,1.000000,0.5,0,0,0.875
4,33-40,Female,NaN,White,NaN,Non-Hispanic,NaN,English,NaN,Some,...,1,1.00,0.66,1.0,1,0.666667,0.5,0,0,0.250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,26-32,Female,NaN,Hispanic,Latinx,Hispanic/Latino of any race,NaN,English,NaN,Some,...,1,1.00,0.33,0.0,1,0.333333,1.0,0,1,0.125
75,18-25,Female,NaN,Hispanic,NaN,Hispanic/Latino of any race,NaN,English,NaN,Some,...,1,0.33,0.66,0.0,0,0.000000,0.5,0,0,0.125
76,18-25,Male,NaN,White,NaN,Non-Hispanic,NaN,English,NaN,Some,...,0,0.33,0.66,1.0,0,0.000000,0.5,0,0,0.375
77,18-25,Female,NaN,Other,NaN,Non-Hispanic,NaN,English,NaN,Some,...,0,0.33,0.00,0.0,0,0.000000,0.0,0,0,0.125
78,26-32,Female,NaN,White,NaN,Non-Hispanic,NaN,English,NaN,Extensive,...,1,0.00,0.00,1.0,0,0.666667,1.0,0,0,0.375

In [34]:
merged_df

,Q25,Q26,Q26_6_TEXT,Q27,Q27_9_TEXT,Q28,Q28_4_TEXT,Q29,Q29_3_TEXT,Q2,...,q23_answers,White,Asian,Hispanic,Male,Female,Age,Primary,Experience,Training
0,33-40,Non-binary,NaN,Asian,NaN,Non-Hispanic,NaN,English,NaN,None,...,0.625,0,1,0,0,0,3,1,0,0
1,41-50,Male,NaN,Other,NaN,Non-Hispanic,NaN,English,NaN,Moderate amount,...,0.125,0,0,0,1,0,4,1,3,0
2,26-32,Female,NaN,Asian,NaN,Other,Tamil Indian,English,NaN,Some,...,0.250,0,1,0,0,1,2,1,2,2
3,26-32,Male,NaN,White,NaN,Non-Hispanic,NaN,English,NaN,Some,...,0.875,1,0,0,1,0,2,1,2,2
4,33-40,Female,NaN,White,NaN,Non-Hispanic,NaN,English,NaN,Some,...,0.250,1,0,0,0,1,3,1,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,26-32,Female,NaN,Hispanic,Latinx,Hispanic/Latino of any race,NaN,English,NaN,Some,...,0.125,0,0,1,0,1,2,1,2,1
75,18-25,Female,NaN,Hispanic,NaN,Hispanic/Latino of any race,NaN,English,NaN,Some,...,0.125,0,0,1,0,1,1,1,2,0
76,18-25,Male,NaN,White,NaN,Non-Hispanic,NaN,English,NaN,Some,...,0.375,1,0,0,1,0,1,1,2,1
77,18-25,Female,NaN,Other,NaN,Non-Hispanic,NaN,English,NaN,Some,...,0.125,0,0,0,0,1,1,1,2,1
78,26-32,Female,NaN,White,NaN,Non-Hispanic,NaN,English,NaN,Extensive,...,0.375,1,0,0,0,1,2,1,4,2

In [6]:
import statsmodels.formula.api as smf

In [30]:
test = merged_df

In [38]:
import pandas as pd

# replace the dummy variable names with the actual race names
test = test.replace({'Hispanic': 'Hispanic', 'Asian': 'Asian', 'White': 'White'})

# create a new categorical variable with "White" as the reference group
test['race'] = pd.Categorical(test[['White', 'Asian', 'Hispanic']].idxmax(axis=1),
                              categories=['Asian', 'Hispanic', 'White'], ordered=True)
test['race'] = test['race'].cat.set_categories(['White', 'Asian', 'Hispanic'], ordered=True)

In [39]:
test

,Q25,Q26,Q26_6_TEXT,Q27,Q27_9_TEXT,Q28,Q28_4_TEXT,Q29,Q29_3_TEXT,Q2,...,White,Asian,Hispanic,Male,Female,Age,Primary,Experience,Training,race
0,33-40,Non-binary,NaN,Asian,NaN,Non-Hispanic,NaN,English,NaN,None,...,0,1,0,0,0,3,1,0,0,Asian
1,41-50,Male,NaN,Other,NaN,Non-Hispanic,NaN,English,NaN,Moderate amount,...,0,0,0,1,0,4,1,3,0,White
2,26-32,Female,NaN,Asian,NaN,Other,Tamil Indian,English,NaN,Some,...,0,1,0,0,1,2,1,2,2,Asian
3,26-32,Male,NaN,White,NaN,Non-Hispanic,NaN,English,NaN,Some,...,1,0,0,1,0,2,1,2,2,White
4,33-40,Female,NaN,White,NaN,Non-Hispanic,NaN,English,NaN,Some,...,1,0,0,0,1,3,1,2,1,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,26-32,Female,NaN,Hispanic,Latinx,Hispanic/Latino of any race,NaN,English,NaN,Some,...,0,0,1,0,1,2,1,2,1,Hispanic
75,18-25,Female,NaN,Hispanic,NaN,Hispanic/Latino of any race,NaN,English,NaN,Some,...,0,0,1,0,1,1,1,2,0,Hispanic
76,18-25,Male,NaN,White,NaN,Non-Hispanic,NaN,English,NaN,Some,...,1,0,0,1,0,1,1,2,1,White
77,18-25,Female,NaN,Other,NaN,Non-Hispanic,NaN,English,NaN,Some,...,0,0,0,0,1,1,1,2,1,White
78,26-32,Female,NaN,White,NaN,Non-Hispanic,NaN,English,NaN,Extensive,...,1,0,0,0,1,2,1,4,2,White

In [41]:
#Real Model 1
model = smf.ols('SC0 ~ q6_answers + q31_answers + q34_answers + q36_answers + q37_answers + q39_answers + q12_answers + q13_answers + q22_answers + q23_answers', data=merged_df)
result = model.fit()
print(result.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    SC0   R-squared:                       0.066
Model:                            OLS   Adj. R-squared:                 -0.072
Method:                 Least Squares   F-statistic:                    0.4770
Date:                Mon, 13 Mar 2023   Prob (F-statistic):              0.899
Time:                        01:28:04   Log-Likelihood:                -212.34
No. Observations:                  79   AIC:                             446.7
Df Residuals:                      68   BIC:                             472.7
Df Model:                          10
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept       8.8449      2.250      3.931      0.000       4.355      13.335
q6_answers      0.0004      1.371      0.000      1.000      -2.736       2.736
q31_answers     0.9210      1.660      0.555      0.581      -2.392       4.234
q34_answers    -1.8170      2.022     -0.899      0.372      -5.851       2.217
q36_answers    -0.2443      1.505     -0.162      0.872      -3.248       2.759
q37_answers     0.8006      0.935      0.856      0.395      -1.065       2.666
q39_answers     2.1335      1.534      1.391      0.169      -0.927       5.194
q12_answers     0.3430      1.685      0.204      0.839      -3.019       3.705
q13_answers    -3.0531      3.931     -0.777      0.440     -10.896       4.790
q22_answers    -0.4230      1.100     -0.384      0.702      -2.619       1.773
q23_answers     0.4385      2.212      0.198      0.843      -3.976       4.853
==============================================================================
Omnibus:                       24.635   Durbin-Watson:                   1.162
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               41.717
Skew:                          -1.202   Prob(JB):                     8.73e-10
Kurtosis:                       5.626   Cond. No.                         20.6
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [40]:
#Real Model 2
model = smf.ols('SC0 ~ q6_answers + q31_answers + q34_answers + q36_answers + q37_answers + q39_answers + q12_answers + q13_answers + q22_answers + q23_answers + Age + Asian + Hispanic + Male + Female + Primary + Experience + Training', data=merged_df)
result = model.fit()
print(result.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    SC0   R-squared:                       0.192
Model:                            OLS   Adj. R-squared:                 -0.051
Method:                 Least Squares   F-statistic:                    0.7907
Date:                Mon, 13 Mar 2023   Prob (F-statistic):              0.703
Time:                        01:26:02   Log-Likelihood:                -206.61
No. Observations:                  79   AIC:                             451.2
Df Residuals:                      60   BIC:                             496.2
Df Model:                          18
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept       7.1289      5.269      1.353      0.181      -3.410      17.668
q6_answers     -0.2170      1.424     -0.152      0.879      -3.066       2.632
q31_answers     1.5686      1.796      0.873      0.386      -2.024       5.162
q34_answers    -2.5792      2.077     -1.242      0.219      -6.733       1.575
q36_answers    -0.3544      1.706     -0.208      0.836      -3.766       3.057
q37_answers     0.5394      1.001      0.539      0.592      -1.464       2.543
q39_answers     2.4352      1.719      1.417      0.162      -1.004       5.874
q12_answers     0.1315      1.829      0.072      0.943      -3.527       3.790
q13_answers    -3.0542      3.957     -0.772      0.443     -10.969       4.861
q22_answers     0.0431      1.156      0.037      0.970      -2.270       2.356
q23_answers     0.8699      2.405      0.362      0.719      -3.941       5.681
Age            -0.7744      0.700     -1.106      0.273      -2.175       0.626
Asian          -0.5529      1.602     -0.345      0.731      -3.758       2.652
Hispanic       -1.9601      2.094     -0.936      0.353      -6.150       2.229
Male            5.1043      3.286      1.554      0.126      -1.468      11.677
Female          3.9242      3.173      1.237      0.221      -2.423      10.271
Primary        -1.1860      2.689     -0.441      0.661      -6.564       4.192
Experience     -0.2364      0.559     -0.423      0.674      -1.355       0.882
Training        1.0567      0.644      1.641      0.106      -0.231       2.345
==============================================================================
Omnibus:                        8.615   Durbin-Watson:                   1.546
Prob(Omnibus):                  0.013   Jarque-Bera (JB):                8.630
Skew:                          -0.626   Prob(JB):                       0.0134
Kurtosis:                       4.027   Cond. No.                         57.5
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [42]:
#Real Model 3
model = smf.ols('SC0 ~ q31_answers + q34_answers + q39_answers + q13_answers + Age + Asian + Hispanic + Male + Female + Primary + Experience + Training', data=merged_df)
result = model.fit()
print(result.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    SC0   R-squared:                       0.185
Model:                            OLS   Adj. R-squared:                  0.036
Method:                 Least Squares   F-statistic:                     1.245
Date:                Mon, 13 Mar 2023   Prob (F-statistic):              0.273
Time:                        01:29:23   Log-Likelihood:                -206.96
No. Observations:                  79   AIC:                             439.9
Df Residuals:                      66   BIC:                             470.7
Df Model:                          12
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept       7.9325      4.363      1.818      0.074      -0.779      16.644
q31_answers     1.5453      1.647      0.938      0.351      -1.743       4.833
q34_answers    -2.9020      1.908     -1.521      0.133      -6.711       0.907
q39_answers     2.6245      1.586      1.655      0.103      -0.542       5.791
q13_answers    -2.9098      3.728     -0.781      0.438     -10.353       4.533
Age            -0.8322      0.635     -1.310      0.195      -2.101       0.436
Asian          -0.7721      1.459     -0.529      0.599      -3.686       2.142
Hispanic       -2.0449      1.755     -1.165      0.248      -5.549       1.459
Male            4.5837      2.914      1.573      0.120      -1.234      10.401
Female          3.5136      2.794      1.258      0.213      -2.065       9.092
Primary        -1.1377      2.323     -0.490      0.626      -5.776       3.500
Experience     -0.2611      0.499     -0.523      0.603      -1.258       0.736
Training        1.1474      0.593      1.936      0.057      -0.036       2.330
==============================================================================
Omnibus:                       10.010   Durbin-Watson:                   1.502
Prob(Omnibus):                  0.007   Jarque-Bera (JB):               10.697
Skew:                          -0.674   Prob(JB):                      0.00476
Kurtosis:                       4.196   Cond. No.                         46.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

End of code